# Generated by Django 6.0.1 on 2026-02-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Autosthetics Car Care', max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('low_stock_limit', models.IntegerField(default=5)),
                ('theme', models.CharField(choices=[('gold', 'Gold'), ('orange', 'Orange'), ('light', 'Light')], default='gold', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
