# Generated by Django 6.0.1 on 2026-02-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklog',
            name='staff',
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
