# Generated by Django 6.0.1 on 2026-02-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stocklog_staff_alter_stocklog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='pc', max_length=20),
        ),
    ]
