# Generated by Django 6.0.1 on 2026-02-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
