# Generated by Django 6.0.1 on 2026-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='stock_type',
            field=models.CharField(max_length=10),
        ),
    ]
