# Generated by Django 6.0.1 on 2026-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dailysnapshot_dailyitemsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
