# Generated by Django 6.0.1 on 2026-02-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockmovement_remarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyitemsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailysnapshot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
