# Generated by Django 6.0.1 on 2026-02-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_dailyitemsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='stock_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10),
        ),
    ]
