# Generated by Django 6.0.1 on 2026-02-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_dailysnapshot_created_at_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='last_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='theme',
            field=models.CharField(choices=[('gold', 'Gold'), ('orange', 'Orange'), ('light', 'Light'), ('dark', 'Dark')], default='gold', max_length=20),
        ),
    ]
