# Generated by Django 6.0.1 on 2026-02-28 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_shopsettings_last_backup_shopsettings_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitemsnapshot',
            name='beginning_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyitemsnapshot',
            name='ending_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyitemsnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dailysnapshot'),
        ),
        migrations.AlterField(
            model_name='dailyitemsnapshot',
            name='stock_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyitemsnapshot',
            name='stock_out',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('box', 'Box'), ('set', 'Set'), ('pair', 'Pair'), ('pack', 'Pack'), ('bag', 'Bag'), ('can', 'Can'), ('bottle', 'Bottle'), ('unit', 'Unit')], default='pcs', max_length=10),
        ),
    ]
