# Generated by Django 6.0.1 on 2026-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
