# Generated by Django 6.0.1 on 2026-04-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_passwordresetotp_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='compatible_units',
            field=models.TextField(blank=True, help_text='List cars this fits', null=True),
        ),
    ]
